version: '3'
services:
  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_ERLANG_COOKIE=DSFGADASGFDSFGDFGASDFGASDFG
    ports:
      - "5672:5672"
      - "15672:15672"